# Generated by Django 3.1.1 on 2020-10-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_categoria', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gru_grupo', models.CharField(max_length=50, verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_sector', models.CharField(max_length=50, verbose_name='Sector')),
                ('sec_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Producto')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('prod_aroma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aroma')),
                ('prod_costo', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CostoUn.')),
                ('prod_markup', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='%Markup')),
                ('prod_stock', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Stock')),
                ('image', models.FileField(blank=True, null=True, upload_to='products/')),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoria')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.grupo')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sector')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='gr_sec_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sector'),
        ),
    ]
